runtime: custom
env: flex

env_variables:
  PYANNOTE_AUTH_TOKEN: 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
  SECRET_KEY: 42e9e2483b4af92719ec4788a107bb70e53fac00386435e7982ecc984e87ae69
  GCS_BUCKET_NAME: nonso-transcriber.appspot.com

resources:
  cpu: 2
  memory_gb: 12
  disk_size_gb: 30

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 5
  cpu_utilization:
    target_utilization: 0.65

handlers:
  - url: /static
    static_dir: static

  - url: /.*
    script: auto

readiness_check:
  app_start_timeout_sec: 3600
