runtime: custom
env: flex

env_variables:
  PYANNOTE_AUTH_TOKEN: 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

resources:
  cpu: 1
  memory_gb: 4
  disk_size_gb: 10

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 5
  cpu_utilization:
    target_utilization: 0.65

handlers:
  - url: /static
    static_dir: static

  - url: /.*
    script: auto
