steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/utils-424517/app-with-ffmpeg", "."]
    dir: "."

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/utils-424517/app-with-ffmpeg"]

  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gcloud config set project utils-424517
        gcloud app deploy --image-url=gcr.io/utils-424517/app-with-ffmpeg --verbosity=debug --quiet

images:
  - "gcr.io/utils-424517/app-with-ffmpeg"
